baseURL = "https://kiera-ember.github.io/beyond-humanity-website/"
languageCode = "en-us"
title = "kieraember"
theme = "beyond-humanity"

[params]
  author = { name = "Kiera N. Ember", siteUrl = "https://kiera-ember.github.io/beyond-humanity-website/" }
  gmaps_url = ""
  [params.footer]
    copyright = "© 2017–{year} Kiera N. Ember"
    
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services.googleAnalytics]
  id = ""

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menu.main]]
  name = "FAQ"
  pageRef = "/faq"
  weight = 10

[[menu.main]]
  name = "Alterhuman Dictionary"
  pageRef = "/alterhuman-dictionary"
  weight = 20

[[menu.main]]
  name = "My Writings"
  pageRef = "/my-writings"
  weight = 30

[[menu.main]]
  name = "Resources"
  pageRef = "/resources"
  weight = 40

[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 50

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true

[privacy]
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true

  [privacy.youTube]
    disable = false
    privacyEnhanced = true